// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: authentication/authen.proto

package authentication

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginID   string `protobuf:"bytes,1,opt,name=LoginID,proto3" json:"LoginID,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	FirstName string `protobuf:"bytes,4,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
}

func (x *RegisterModel) Reset() {
	*x = RegisterModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModel) ProtoMessage() {}

func (x *RegisterModel) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModel.ProtoReflect.Descriptor instead.
func (*RegisterModel) Descriptor() ([]byte, []int) {
	return file_authentication_authen_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterModel) GetLoginID() string {
	if x != nil {
		return x.LoginID
	}
	return ""
}

func (x *RegisterModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterModel) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterModel) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

type LoginModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginID  string `protobuf:"bytes,1,opt,name=LoginID,proto3" json:"LoginID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *LoginModel) Reset() {
	*x = LoginModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginModel) ProtoMessage() {}

func (x *LoginModel) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginModel.ProtoReflect.Descriptor instead.
func (*LoginModel) Descriptor() ([]byte, []int) {
	return file_authentication_authen_proto_rawDescGZIP(), []int{1}
}

func (x *LoginModel) GetLoginID() string {
	if x != nil {
		return x.LoginID
	}
	return ""
}

func (x *LoginModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Duratation int32  `protobuf:"varint,2,opt,name=Duratation,proto3" json:"Duratation,omitempty"`
}

func (x *JWT) Reset() {
	*x = JWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_authentication_authen_proto_rawDescGZIP(), []int{2}
}

func (x *JWT) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *JWT) GetDuratation() int32 {
	if x != nil {
		return x.Duratation
	}
	return 0
}

var File_authentication_authen_proto protoreflect.FileDescriptor

var file_authentication_authen_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x0d, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0a, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x37, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x51, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32, 0x81, 0x01, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x57, 0x54, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x12, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4a, 0x57, 0x54, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authentication_authen_proto_rawDescOnce sync.Once
	file_authentication_authen_proto_rawDescData = file_authentication_authen_proto_rawDesc
)

func file_authentication_authen_proto_rawDescGZIP() []byte {
	file_authentication_authen_proto_rawDescOnce.Do(func() {
		file_authentication_authen_proto_rawDescData = protoimpl.X.CompressGZIP(file_authentication_authen_proto_rawDescData)
	})
	return file_authentication_authen_proto_rawDescData
}

var file_authentication_authen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authentication_authen_proto_goTypes = []interface{}{
	(*RegisterModel)(nil), // 0: authentication.RegisterModel
	(*LoginModel)(nil),    // 1: authentication.LoginModel
	(*JWT)(nil),           // 2: authentication.JWT
	(*empty.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_authentication_authen_proto_depIdxs = []int32{
	0, // 0: authentication.Resgister.Resgister:input_type -> authentication.RegisterModel
	1, // 1: authentication.Login.Login:input_type -> authentication.LoginModel
	2, // 2: authentication.Login.CheckAuthen:input_type -> authentication.JWT
	3, // 3: authentication.Resgister.Resgister:output_type -> google.protobuf.Empty
	2, // 4: authentication.Login.Login:output_type -> authentication.JWT
	3, // 5: authentication.Login.CheckAuthen:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_authen_proto_init() }
func file_authentication_authen_proto_init() {
	if File_authentication_authen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authentication_authen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authentication_authen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_authentication_authen_proto_goTypes,
		DependencyIndexes: file_authentication_authen_proto_depIdxs,
		MessageInfos:      file_authentication_authen_proto_msgTypes,
	}.Build()
	File_authentication_authen_proto = out.File
	file_authentication_authen_proto_rawDesc = nil
	file_authentication_authen_proto_goTypes = nil
	file_authentication_authen_proto_depIdxs = nil
}
